server:
  port: 8080
  host: localhost
  read_timeout: 30s
  write_timeout: 30s

neo4j:
  uri: bolt://localhost:7687
  username: neo4j
  password: password
  max_connection_pool_size: 50
  max_transaction_retry_time: 30s

generators:
  mysql:
    template_path: config/templates/mysql.yml
    default_engine: InnoDB
    default_charset: utf8mb4
  postgresql:
    template_path: config/templates/postgresql.yml
    default_schema: public
  sqlite:
    template_path: config/templates/sqlite.yml
    wal_mode: true

design:
  auto_save: true
  auto_save_interval: 30s
  max_nodes: 100
  max_relationships: 200
  max_properties_per_node: 50

logging:
  level: info
  format: json
  output: stdout

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Content-Type
    - Authorization
